module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    maxWidth: {
      footer: '1180px',
      else: '1244px',
    },
    extend: {
      colors: {
        blue: 'var(--blue)',
        indigo: 'var(--indigo)',
        purple: 'var(--purple)',
        pink: 'var(--pink)',
        red: 'var(--red)',
        orange: 'var(--orange)',
        yellow: 'var(--yellow)',
        green: 'var(--green)',
        teal: 'var(--teal)',
        cyan: 'var(--cyan)',
        white: 'var(--white)',
        gray: 'var(--gray)',
        grayDark: 'var(--gray-dark)',
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        success: 'var(--success)',
        info: 'var(--info)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        light: 'var(--light)',
        dark: 'var(--dark)',
        breakpointXS: 'var(--breakpoint-xs)',
        breakpointSM: 'var(--breakpoint-sm)',
        breakpointMD: 'var(--breakpoint-md)',
        breakpointLG: 'var(--breakpoint-lg)',
        breakpointXL: 'var(--breakpoint-xl)',
      },
    },
  },
  plugins: [],
};
